# Generated by Django 3.1.4 on 2021-01-15 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=300)),
                ('subject', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
